Models/ErrorViewModel.cs
namespace ASPnetAPIrest.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Todo.cs
using System.ComponentModel.DataAnnotations;
using Todos.Validators;

namespace ASPnetAPIrest.Models;

public class Todo
{
    public int Id { get; set; }

    [Display(Name = "Título")]
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [StringLength(100, MinimumLength = 3, ErrorMessage = "O campo {0} deve ter entre {2} e {1} caracteres")]
    public string Title { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }

    [Display(Name = "Data de Entrega")]
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    [FutureOrPresent]
    public DateOnly Deadline { get; set; }
    public DateOnly? FinishedAt { get; set; }

    public void Finish()
    {
        FinishedAt = DateOnly.FromDateTime(DateTime.Now);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPnetAPIrest.Models;

namespace ASPnetAPIrest.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TodoController.cs
using ASPnetAPIrest.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPnetAPIrest.Controllers;

public class TodoController : Controller
{
    private readonly TodosContext _context;

    public TodoController(TodosContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        ViewData["Title"] = "Lista de Tarefas";
        var todos = _context.Todos.ToList();
        return View(todos);
    }

    public IActionResult Create()
    {
        ViewData["Title"] = "Nova Tarefa";
        return View("Form");
    }

    [HttpPost]
    public IActionResult Create(Todo todo)
    {
        if (ModelState.IsValid)
        {
            todo.CreatedAt = DateTime.Now;
            _context.Todos.Add(todo);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        ViewData["Title"] = "Nova Tarefa";
        return View("Form", todo);
    }

    public IActionResult Edit(int id)
    {
        var todo = _context.Todos.Find(id);
        if (todo is null)
        {
            return NotFound();
        }
        ViewData["Title"] = "Editar Tarefa";
        return View("Form", todo);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Todo todo)
    {
        if (!ModelState.IsValid)
        {
            ViewData["Title"] = "Editar Tarefa";
            return View("Form", todo);
        }
        var todoDb = _context.Todos.FirstOrDefault(t => t.Id == todo.Id);
        
        if (todoDb == null)
            return NotFound();
        
        todoDb.Title = todo.Title;
        todoDb.Deadline = todo.Deadline;
        
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int id)
    {
        var todo = _context.Todos.Find(id);
        if (todo is null)
        {
            return NotFound();
        }
        ViewData["Title"] = "Excluir Tarefa";
        return View(todo);
    }

    [HttpPost]
    public IActionResult Delete(Todo todo)
    {
        _context.Todos.Remove(todo);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Finish(int id)
    {
        var todo = _context.Todos.Find(id);
        if (todo is null)
        {
            return NotFound();
        }
        todo.Finish();
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPnetAPIrest</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPnetAPIrest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPnetAPIrest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - ASPnetAPIrest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Todo/Delete.cshtml
@model ASPnetAPIrest.Models.Todo

<h1>@ViewData["Title"]</h1>

<p>Tem certeza que deseja excluir a tarefa <strong>@Model.Title</strong>?</p>

<form method="POST">
  <button class="btn btn-danger" type="submit">Excluir</button>
  <a asp-controller="Todo" asp-action="Index" class="btn btn-primary">Cancelar</a>
</form>

Views/Todo/Form.cshtml
@model ASPnetAPIrest.Models.Todo;

<h1>@ViewData["Title"]</h1>

<form method="POST">
  <div class="mb-3">
    <label asp-for="Title">Título</label>
    <input asp-for="Title" class="form-control">
    <span asp-validation-for="Title" class="text-danger"></span>
  </div>

  <div class="mb-3">
    <label asp-for="Deadline">Data de entrega</label>
    <input asp-for="Deadline" type="date" class="form-control">
    <span asp-validation-for="Deadline" class="text-danger"></span>
  </div>

  <button class="btn btn-primary" type="submit">Salvar</button>
</form>

Views/Todo/Index.cshtml
@model List<ASPnetAPIrest.Models.Todo>

<h1>@ViewData["Title"]</h1>

@if (Model.Count > 0)
{
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Título</th>
            <th scope="col">Criado em</th>
            <th scope="col">Data de entrega</th>
            <th scope="col">Finalizado em</th>
            <th scope="col">Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var todo in Model)
        {
            <tr>
            <td>@todo.Id</td>
            <td>@todo.Title</td>
            <td>@todo.CreatedAt</td>
            <td>@todo.Deadline</td>
            <td>
                @(todo.FinishedAt.HasValue ? todo.FinishedAt : "-")
            </td>
            <td>
                <a
                asp-controller="Todo"
                asp-action="Finish"
                asp-route-id="@todo.Id"
                class="btn btn-success btn-sm @(todo.FinishedAt.HasValue ? "disabled" : "")"
                >
                Concluir
                </a>
                <a
                asp-controller="Todo"
                asp-action="Edit"
                asp-route-id="@todo.Id"
                class="btn btn-warning btn-sm @(todo.FinishedAt.HasValue ? "disabled" : "")"
                >
                Editar
                </a>
                <a
                asp-controller="Todo"
                asp-action="Delete"
                asp-route-id="@todo.Id"
                class="btn btn-danger btn-sm"
                >
                Excluir
                </a>
            </td>
            </tr>
        }
        </tbody>
    </table>
} else {
  <p>Nenhuma tarefa cadastrada</p>
}


<a asp-controller="Todo" asp-action="Create" class="btn btn-primary">Nova Tarefa</a>